[project]
name = "tps-laval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jean-Louis GUENEGO", email = "jlguenego@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "onnx>=1.23.0",
    "onnxruntime>=1.30.0",
    "onnxscript>=0.7.2",
    "pandas>=3.0.6",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.29.0",
]

[project.scripts]
tps-laval = "tps_laval:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
