[project]
name = "tps-laval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jean-Louis GUENEGO", email = "jlguenego@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tps-laval = "tps_laval:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
